# Generated by Django 4.2 on 2023-04-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('doc', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptiveFate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Captive fate',
                'verbose_name_plural': 'Captive fates',
            },
        ),
        migrations.CreateModel(
            name='CaptiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Captive status',
                'verbose_name_plural': 'Captive statuses',
            },
        ),
        migrations.CreateModel(
            name='Enslaved',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('documented_name', models.CharField(blank=True, max_length=100)),
                ('name_first', models.CharField(blank=True, max_length=100, null=True)),
                ('name_second', models.CharField(blank=True, max_length=100, null=True)),
                ('name_third', models.CharField(blank=True, max_length=100, null=True)),
                ('modern_name', models.CharField(blank=True, max_length=100, null=True)),
                ('editor_modern_names_certainty', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(db_index=True, null=True)),
                ('gender', models.IntegerField(db_index=True, null=True)),
                ('height', models.DecimalField(db_index=True, decimal_places=2, max_digits=6, null=True, verbose_name='Height in inches')),
                ('skin_color', models.CharField(db_index=True, max_length=100, null=True)),
                ('notes', models.CharField(max_length=8192, null=True)),
                ('dataset', models.IntegerField(db_index=True, default=0)),
                ('captive_fate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.captivefate')),
                ('captive_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.captivestatus')),
            ],
        ),
        migrations.CreateModel(
            name='EnslaverIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_alias', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255, null=True)),
                ('father_occupation', models.CharField(max_length=255, null=True)),
                ('mother_name', models.CharField(max_length=255, null=True)),
                ('probate_date', models.CharField(max_length=12, null=True)),
                ('will_value_pounds', models.CharField(max_length=12, null=True)),
                ('will_value_dollars', models.CharField(max_length=12, null=True)),
                ('will_court', models.CharField(max_length=12, null=True)),
                ('text_id', models.CharField(max_length=50)),
                ('first_active_year', models.IntegerField(null=True)),
                ('last_active_year', models.IntegerField(null=True)),
                ('number_enslaved', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Enslaver unique identity and personal info',
            },
        ),
        migrations.CreateModel(
            name='LanguageGroup',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.place')),
            ],
            options={
                'verbose_name': 'Geo-Coded Language Group',
                'verbose_name_plural': 'Geo-Coded Language Groups',
            },
            bases=('geo.place',),
        ),
        migrations.CreateModel(
            name='ModernCountry',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.place')),
            ],
            options={
                'verbose_name': 'Modern Country',
                'verbose_name_plural': 'Modern Countries',
            },
            bases=('geo.place',),
        ),
        migrations.CreateModel(
            name='RegisterCountry',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.place')),
            ],
            options={
                'verbose_name': 'Register country',
                'verbose_name_plural': 'Register countries',
            },
            bases=('geo.place',),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Enslaver role',
                'verbose_name_plural': 'Enslaver roles',
            },
        ),
        migrations.CreateModel(
            name='PersonEventConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_person_connection', to='event.event')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_with_role', to='past.role')),
            ],
            options={
                'verbose_name': 'Enslaved Person in event',
                'verbose_name_plural': 'Enslaved People in events',
            },
        ),
        migrations.CreateModel(
            name='EnslaverLinkedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('authority', models.CharField(max_length=255)),
                ('enslaver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enslaver_linked_data', to='past.enslaveridentity')),
            ],
            options={
                'verbose_name': 'Enslaver links',
                'verbose_name_plural': 'Enslaver links',
            },
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslavers_born_now', to='past.personeventconnection'),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='death',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslavers_died_now', to='past.personeventconnection'),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='marriages',
            field=models.ManyToManyField(to='past.personeventconnection'),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='principal_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enslaver_principal_location', to='geo.place'),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='references',
            field=models.ManyToManyField(to='doc.reference'),
        ),
        migrations.CreateModel(
            name='EnslaverAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('uid', models.IntegerField(unique=True)),
                ('enslavement_events', models.ManyToManyField(to='past.personeventconnection')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='past.enslaveridentity')),
            ],
            options={
                'verbose_name': 'Enslaver alias',
            },
        ),
        migrations.CreateModel(
            name='EnslavedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=3)),
                ('recordings_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Enslaved name',
                'verbose_name_plural': 'Enslaved names',
                'unique_together': {('name', 'language')},
            },
        ),
        migrations.CreateModel(
            name='EnslavedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('authority', models.CharField(max_length=255)),
                ('enslaved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enslaved_linked_data', to='past.enslaved')),
            ],
            options={
                'verbose_name': 'Enslaved links',
                'verbose_name_plural': 'Enslaved links',
            },
        ),
        migrations.AddField(
            model_name='enslaved',
            name='enslavement_events',
            field=models.ManyToManyField(to='past.personeventconnection'),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='language_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_people_with_language_group_here', to='past.languagegroup'),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='last_known_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.date'),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='post_disembark_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_people_who_ended_up_here', to='geo.place'),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='references',
            field=models.ManyToManyField(to='doc.reference'),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='register_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_people_registered_with_this_country', to='past.registercountry'),
        ),
    ]
