# Generated by Django 4.2 on 2023-04-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enslaveralias',
            options={'verbose_name': 'Enslaver alias', 'verbose_name_plural': 'Enslaver aliases'},
        ),
        migrations.AlterModelOptions(
            name='enslaveridentity',
            options={'verbose_name': 'Enslaver Identity', 'verbose_name_plural': 'Enslaver Identities'},
        ),
    ]
