# Generated by Django 4.2 on 2023-04-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0002_alter_enslaveralias_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personeventconnection',
            options={'verbose_name': 'Person in event', 'verbose_name_plural': 'People in events'},
        ),
    ]
