# Generated by Django 4.0.2 on 2022-07-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0009_alter_broadregion_options_alter_region_options_and_more'),
        ('past', '0004_external_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaveridentity',
            name='birth_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.place'),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='death_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.place'),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='principal_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.place'),
        ),
        migrations.AlterField(
            model_name='enslavermerger',
            name='birth_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.place'),
        ),
        migrations.AlterField(
            model_name='enslavermerger',
            name='death_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.place'),
        ),
        migrations.AlterField(
            model_name='enslavermerger',
            name='principal_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.place'),
        ),
    ]
