# Generated by Django 4.2.1 on 2023-10-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagecargoconnection',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.cargotype'),
        ),
        migrations.AlterField(
            model_name='voyagecargoconnection',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voyage.cargounit'),
        ),
        migrations.AlterField(
            model_name='voyagecargoconnection',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.voyage'),
        ),
    ]
