# Generated by Django 4.2.1 on 2023-11-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagecargoconnection',
            name='is_purchasing_commmodity',
            field=models.BooleanField(blank=True, default=False, verbose_name='Was this a commodity used to purchase enslaved people'),
        ),
    ]
