# Generated by Django 4.2.1 on 2023-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagecargoconnection',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='The amount of cargo according to the unit'),
        ),
    ]
