# Generated by Django 4.2.1 on 2023-10-25 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rigofvessel',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='tontype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='african_info',
            field=models.ManyToManyField(to='voyage.africaninfo'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='cargo',
            field=models.ManyToManyField(related_name='+', through='voyage.VoyageCargoConnection', to='voyage.cargotype'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.voyagecrew'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_dates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.voyagedates'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_groupings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.voyagegroupings'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.voyageitinerary'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.voyageoutcome'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.voyageship'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_slaves_numbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.voyageslavesnumbers'),
        ),
        migrations.AlterField(
            model_name='voyagegroupings',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
