# Generated by Django 4.2.1 on 2023-10-30 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_alter_voyagecargoconnection_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagecargoconnection',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_cargo', to='voyage.voyage'),
        ),
    ]
