# Generated by Django 4.2.1 on 2023-10-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_alter_voyagecargoconnection_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyageitinerary',
            name='voyage',
        ),
    ]
