# Generated by Django 4.2.1 on 2023-10-28 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_remove_voyageitinerary_voyage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyageslavesnumbers',
            name='voyage',
        ),
    ]
