# Generated by Django 4.2.1 on 2023-10-30 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_alter_voyagecargoconnection_voyage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='voyagecargoconnection',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='voyage.voyage'),
        ),
    ]
