# Generated by Django 4.2.1 on 2023-06-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_alter_voyage_managers_rename_label_nationality_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagesources',
            name='transkribus_docid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
