# Generated by Django 4.2.1 on 2023-06-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_doctest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesourcestype',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
    ]
