# Generated by Django 4.2.1 on 2023-06-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0004_alter_voyagesourcestype_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyagesourcesconnection',
            name='zotero_source',
        ),
    ]
