# Generated by Django 4.2.1 on 2023-10-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0004_remove_voyage_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='african_info',
            field=models.ManyToManyField(related_name='african_info_voyages', to='voyage.africaninfo'),
        ),
    ]
