# Generated by Django 4.2.1 on 2024-04-16 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_alter_nationality_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rigofvessel',
            name='name',
            field=models.CharField(db_index=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='voyagegroupings',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='voyagesparsedate',
            name='day',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='voyagesparsedate',
            name='month',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='voyagesparsedate',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
