# Generated by Django 4.2.1 on 2023-06-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0006_alter_broadregion_geo_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationality',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owneroutcome',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='particularoutcome',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resistance',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rigofvessel',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='slavesoutcome',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tontype',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vesselcapturedoutcome',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='voyagegroupings',
            old_name='label',
            new_name='name',
        ),
    ]
