# Generated by Django 4.2.1 on 2023-09-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_location_child_of'),
        ('voyage', '0006_alter_voyagedates_arrival_at_second_place_landing_sparsedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadregion',
            name='geo_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.location', verbose_name='New Location Fieldmapping'),
        ),
        migrations.AlterField(
            model_name='place',
            name='geo_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.location', verbose_name='New Location Fieldmapping'),
        ),
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voyage.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='broad_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='voyage.broadregion'),
        ),
        migrations.AlterField(
            model_name='region',
            name='geo_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.location', verbose_name='New Location Fieldmapping'),
        ),
    ]
