# Generated by Django 4.2.1 on 2023-08-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_sparsedate_day_alter_sparsedate_month_and_more'),
        ('voyage', '0006_alter_voyagedates_arrival_at_second_place_landing_sparsedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagedates',
            name='arrival_at_second_place_landing_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Date of arrival at second place of landing (DATARR37,36,38)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='date_departed_africa_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Date vessel departed Africa (DATELEFTAFR)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='departure_last_place_of_landing_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Date of departure from last place of landing (DDEPAMB,*,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='first_dis_of_slaves_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Date of first disembarkation of slaves (DATARR33,32,34)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='imp_arrival_at_port_of_dis_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Year of arrival at port of disembarkation (YEARAM)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='imp_departed_africa_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Year departed Africa'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='imp_voyage_began_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Year voyage began'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='slave_purchase_began_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Date that slave purchase began (D1SLATRB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='third_dis_of_slaves_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Date of third disembarkation of slaves (DATARR40,39,41)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='vessel_left_port_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Date that vessel left last slaving port (DLSLATRB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='voyage_began_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Date that voyage began (DATEDEPB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='voyage_completed_sparsedate',
            field=models.ForeignKey(blank=True, help_text='Date in format: MM,DD,YYYY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.sparsedate', verbose_name='Date on which slave voyage completed (DATARR44,43,45)'),
        ),
    ]
