# Generated by Django 4.2.1 on 2023-09-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0007_alter_broadregion_geo_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyageitinerary',
            name='broad_region_of_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broad_region_of_return', to='voyage.broadregion', verbose_name='Broad region of return (RETRNREG1)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='first_landing_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_landing_place', to='voyage.place', verbose_name='First place of slave landing (SLA1PORT)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='first_landing_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_landing_region', to='voyage.region', verbose_name='First region of slave landing (REGDIS1)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='first_place_slave_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_place_slave_purchase', to='voyage.place', verbose_name='First place of slave purchase (PLAC1TRA)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='first_region_slave_emb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_region_slave_emb', to='voyage.region', verbose_name='First region of embarkation of slaves (REGEM1)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='imp_broad_region_of_slave_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_broad_region_of_slave_purchase', to='voyage.broadregion', verbose_name='Imputed principal broad region of slave purchase (MAJBYIMP1)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='imp_broad_region_slave_dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_broad_region_slave_dis', to='voyage.broadregion', verbose_name='Imputed broad region of slave disembarkation (MJSELIMP1)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='imp_broad_region_voyage_begin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_broad_region_voyage_begin', to='voyage.broadregion', verbose_name='Imputed broad region where voyage began (DEPTREGIMP1)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='imp_port_voyage_begin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_port_voyage_begin', to='voyage.place', verbose_name='Imputed port where voyage began (PTDEPIMP)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='imp_principal_place_of_slave_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_principal_place_of_slave_purchase', to='voyage.place', verbose_name='Imputed principal place of slave purchase (MJBYPTIMP)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='imp_principal_port_slave_dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_principal_port_slave_dis', to='voyage.place', verbose_name='Imputed principal port of slave disembarkation (MJSLPTIMP)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='imp_principal_region_of_slave_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_principal_region_of_slave_purchase', to='voyage.region', verbose_name='Imputed principal region of slave purchase (MAJBYIMP)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='imp_principal_region_slave_dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_principal_region_slave_dis', to='voyage.region', verbose_name='Imputed principal region of slave disembarkation (MJSELIMP)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='imp_region_voyage_begin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imp_region_voyage_begin', to='voyage.region', verbose_name='Imputed region where voyage began (DEPTREGIMP)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_first_port_dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_first_port_dis', to='voyage.place', verbose_name='First intended port of disembarkation (ARRPORT)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_first_port_emb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_first_port_emb', to='voyage.place', verbose_name='First intended port of embarkation (EMBPORT)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_first_region_purchase_slaves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_first_region_purchase_slaves', to='voyage.region', verbose_name='First intended region of purchase of slaves (EMBREG)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_first_region_slave_landing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_first_region_slave_landing', to='voyage.region', verbose_name='First intended region of slave landing (REGARR)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_fourth_place_region_slave_landing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_fourth_region_slave_landing', to='voyage.region', verbose_name='Fourth intended region of slave landing (REGARR4)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_fourth_port_dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_fourth_port_dis', to='voyage.place', verbose_name='Fourth intended port of disembarkation (ARRPORT4)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_second_place_region_slave_landing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_second_region_slave_landing', to='voyage.region', verbose_name='Second intended region of slave landing (REGARR2)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_second_port_dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_second_port_dis', to='voyage.place', verbose_name='Second intended port of disembarkation (ARRPORT2)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_second_port_emb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_second_port_emb', to='voyage.place', verbose_name='Second intended port of embarkation (EMBPORT2)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_second_region_purchase_slaves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_second_region_purchase_slaves', to='voyage.region', verbose_name='Second intended region of purchase of slaves (EMBREG2)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_third_place_region_slave_landing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_third_region_slave_landing', to='voyage.region', verbose_name='Third intended region of slave landing (REGARR3)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='int_third_port_dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='int_third_port_dis', to='voyage.place', verbose_name='Third intended port of disembarkation (ARRPORT3)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='place_voyage_ended',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_voyage_ended', to='voyage.place', verbose_name='Place at which voyage ended (PORTRET)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='port_of_call_before_atl_crossing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_of_call_before_atl_crossing', to='voyage.place', verbose_name='Port of call before Atlantic crossing (NPAFTTRA)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='port_of_departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_of_departure', to='voyage.place', verbose_name='Port of departure (PORTDEP)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='principal_place_of_slave_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_place_of_slave_purchase', to='voyage.place', verbose_name='Principal place of slave purchase (MAJBUYPT)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='principal_port_of_slave_dis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_port_of_slave_dis', to='voyage.place', verbose_name='Principal port of slave disembarkation (MAJSELPT)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='region_of_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_of_return', to='voyage.region', verbose_name='Region of return (RETRNREG)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='second_landing_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_landing_place', to='voyage.place', verbose_name='Second place of slave landing (ADPSALE1)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='second_landing_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_landing_region', to='voyage.region', verbose_name='Second region of slave landing (REGDIS2)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='second_place_slave_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place_slave_purchase', to='voyage.place', verbose_name='Second place of slave purchase (PLAC2TRA)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='second_region_slave_emb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_region_slave_emb', to='voyage.region', verbose_name='Second region of embarkation of slaves (REGEM2)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='third_landing_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_landing_place', to='voyage.place', verbose_name='Third place of slave landing (ADPSALE2)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='third_landing_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_landing_region', to='voyage.region', verbose_name='Third region of slave landing (REGDIS3)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='third_place_slave_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place_slave_purchase', to='voyage.place', verbose_name='Third place of slave purchase (PLAC3TRA)'),
        ),
        migrations.AlterField(
            model_name='voyageitinerary',
            name='third_region_slave_emb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_region_slave_emb', to='voyage.region', verbose_name='Third region of embarkation of slaves (REGEM3)'),
        ),
    ]
