# Generated by Django 4.2 on 2023-04-18 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(31)])),
                ('m', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(12)])),
                ('y', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(3000)])),
                ('h', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(24)])),
                ('imputed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtype')),
                ('finish_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_ended_on_this_date', to='event.date')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.place')),
                ('references', models.ManyToManyField(to='doc.reference')),
                ('start_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_begun_on_this_date', to='event.date')),
            ],
        ),
    ]
