# Generated by Django 4.2 on 2023-04-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='imputed',
            field=models.BooleanField(default=False),
        ),
    ]
