# Generated by Django 4.2.1 on 2023-06-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interimvoyage',
            options={'verbose_name': 'Voyage', 'verbose_name_plural': 'Voyages'},
        ),
    ]
