# Generated by Django 4.2.1 on 2023-08-02 18:42

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=300, null=True, verbose_name='Thumbnail'),
        ),
    ]
