# Generated by Django 4.2.1 on 2023-08-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_authors', to='blog.institution'),
        ),
    ]
