# Generated by Django 4.0.2 on 2022-07-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_doc_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='source',
        ),
    ]
