# Generated by Django 4.2.1 on 2025-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_docsparsedate_day_alter_docsparsedate_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='bib',
            field=models.TextField(blank=True, db_index=True, help_text='Formatted bibliography for the Document', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='text',
            field=models.TextField(db_index=True),
        ),
    ]
