# Generated by Django 4.2.1 on 2025-06-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_docsparsedate_day_alter_docsparsedate_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='zotero_item_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zotero Alphanumeric Item ID'),
        ),
    ]
