# from __future__ import unicode_literals
# 
# from django.urls import re_path
# from django.views.generic import TemplateView
# 
# from contribute import views
# # from voyages.apps import past
# 
# urlpatterns = [
#     re_path(r'^$', views.index, name='index'),
#     re_path(r'^guidelines',
#         TemplateView.as_view(template_name='contribute/guidelines.html'),
#         name='guidelines'),
#     re_path(r'^thanks',
#         TemplateView.as_view(template_name='contribute/thanks.html'),
#         name='thanks'),
#     re_path(r'^delete_voyage', views.delete, name='delete_voyage'),
#     re_path(r'^delete_review/(?P<contribution_id>\d+)',
#         views.delete_review,
#         name='delete_review'),
#     re_path(r'^places_ajax', views.get_places, name='places_ajax'),
#     re_path(r'^voyage_ajax', views.get_voyage_by_id, name='voyage_ajax'),
#     re_path(r'^interim/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)/'
#         r'save_ajax$',
#         views.interim_save_ajax,
#         name='interim_save_ajax'),
#     re_path(r'interim/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)',
#         views.interim,
#         name='interim'),
#     re_path(r'interim_commit/(?P<contribution_type>\w+)/(?P<contribution_id>\d+)',
#         views.interim_commit,
#         name='interim_commit'),
#     re_path(r'interim_summary/(?P<contribution_type>\w+)/'
#         r'(?P<contribution_id>\d+)$',
#         views.interim_summary,
#         name='interim_summary'),
#     re_path(r'interim_summary/(?P<contribution_type>\w+)/'
#         r'(?P<contribution_id>\d+)/(?P<mode>reviewer)$',
#         views.interim_summary,
#         name='interim_summary_reviewer'),
#     re_path(r'interim_summary/(?P<contribution_type>\w+)/'
#         r'(?P<contribution_id>\d+)/(?P<mode>editor)$',
#         views.interim_summary,
#         name='interim_summary_editor'),
#     re_path(r'legal', views.legal, name='legal'),
# #     re_path(r'enslaver_contribution_review/(?P<pk>\d+)$',
# #         past.views.enslaver_contrib_editorial_review,
# #         name='enslaver_contrib_editorial_review'),
#     re_path(r'edit_voyage', views.edit, name='edit_voyage'),
#     re_path(r'merge_voyages', views.merge, name='merge_voyages'),
#     re_path(r'new_voyage', views.new_voyage, name='new_voyage'),
#     re_path(r'editor_main/(?P<active_tab>\w*)$', views.editor_main),
#     re_path(r'editor_main', views.editor_main, name='editor_main'),
#     re_path(r'review_request/(?P<review_request_id>\d+)',
#         views.review_request,
#         name='review_request'),
#     re_path(r'reply_review_request',
#         views.reply_review_request,
#         name='reply_review_request'),
#     re_path(r'editorial_review/(?P<editor_contribution_id>\d+)/save_ajax',
#         views.editorial_review_interim_save_ajax,
#         name='editorial_review_interim_save_ajax'),
#     re_path(r'editorial_review/(?P<editor_contribution_id>\d+)'
#         r'/submit_editorial_decision',
#         views.submit_editorial_decision,
#         name='submit_editorial_decision'),
#     re_path(r'editorial_review/(?P<review_request_id>\d+)',
#         views.editorial_review,
#         name='editorial_review'),
#     re_path(r'editorial_sources', views.editorial_sources,
#         name='editorial_sources'),
#     re_path(r'begin_editorial_review',
#         views.begin_editorial_review,
#         name='begin_editorial_review'),
#     re_path(r'review/(?P<reviewer_contribution_id>\d+)/save_ajax',
#         views.review_interim_save_ajax,
#         name='review_interim_save_ajax'),
#     re_path(r'review/(?P<review_request_id>\d+)/submit_review_to_editor',
#         views.submit_review_to_editor,
#         name='submit_review_to_editor'),
#     re_path(r'review/(?P<review_request_id>\d+)', views.review, name='review'),
#     re_path(r'json_pending_requests',
#         views.get_pending_requests,
#         name='json_pending_requests'),
#     re_path(r'json_pending_publication',
#         views.get_pending_publication,
#         name='json_pending_publication'),
#     re_path(r'json_reviewers', views.get_reviewers, name='json_reviewers'),
#     re_path(r'json_publish_pending',
#         views.publish_pending,
#         name='json_publish_pending'),
#     re_path(r'json_retrieve_publication_status',
#         views.retrieve_publication_status,
#         name='json_retrieve_publication_status'),
#     re_path(r'download_voyages_status',
#         views.download_voyages_status,
#         name='download_voyages_status'),
#     re_path(r'download_voyages_go',
#         views.download_voyages_go,
#         name='download_voyages_go'),
#     re_path(r'download_voyages', views.download_voyages, name='download_voyages'),
#     re_path(r'post_review_request',
#         views.post_review_request,
#         name='post_review_request'),
#     re_path(r'post_archive_review_request',
#         views.post_archive_review_request,
#         name='post_archive_review_request'),
#     re_path(r'impute_contribution/(?P<editor_contribution_id>\d+)',
#         views.impute_contribution,
#         name='impute_contribution'),
#     # African Origins contribution backend API
#     re_path(r'list_origins_contributions',
#         views.get_origins_contributions,
#         name='list_origins_contributions'),
#     re_path(r'origins_contribution_details/(?P<contrib_pk>\d+)$',
#         views.get_origins_contrib_details,
#         name='origins_contribution_details'),
#     re_path(r'reject_origins_contribution',
#         views.reject_origins_contribution,
#         name='reject_origins_contribution'),
#     re_path(r'publish_origins_editorial_review',
#         views.publish_origins_editorial_review,
#         name='publish_origins_editorial_review'),
#     re_path(r'voyage_summary/(?P<pk>\d+)$',
#         views.get_voyage_summary,
#         name='get_voyage_summary'),
#     re_path(r'init_enslaver_interim',
#         views.init_enslaver_interim,
#         name='init_enslaver_interim'),
#     re_path(r'enslaver_update_actions',
#         views.get_enslaver_update_actions,
#         name='get_enslaver_update_actions'),
#     re_path(r'submit_enslaver_contribution',
#         views.submit_enslaver_contribution,
#         name='submit_enslaver_contribution'),
#     re_path(r'enslaver_contribution_list',
#         views.get_enslaver_contribution_list,
#         name='get_enslaver_contribution_list'),
#     re_path(r'submit_enslaver_editorial_review',
#         views.submit_enslaver_editorial_review,
#         name='submit_enslaver_editorial_review'),
#     re_path(r'review_origins_contrib/(?P<pk>\d+)$',
#         views.review_origins_contrib,
#         name='review_origins_contrib'),
#     re_path(r'language_choices',
#         views.get_language_choices,
#         name='language_choices')
# ]
