# Generated by Django 4.2.1 on 2024-06-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='value',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='SPSS code'),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Geographic Location Type'),
        ),
    ]
