# Generated by Django 4.2.1 on 2023-11-03 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Geographic Location Type')),
            ],
            options={
                'verbose_name': 'Geographic Location Type',
                'verbose_name_plural': 'Geographic Location Types',
            },
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.JSONField(blank=True, null=True, verbose_name='Geojson Polygon')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Location name')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude of Centroid')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude of Centroid')),
                ('value', models.IntegerField(unique=True, verbose_name='SPSS code')),
                ('location_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_location', to='geo.locationtype', verbose_name='Location Type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='geo.location', verbose_name='Child of')),
                ('spatial_extent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.polygon', verbose_name='Polygon')),
            ],
            options={
                'verbose_name': 'Geographic Location',
                'verbose_name_plural': 'Geographic Locations',
                'ordering': ['value'],
            },
        ),
    ]
