# Generated by Django 4.2.1 on 2023-06-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location name')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude of Centroid')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude of Centroid')),
                ('value', models.IntegerField(unique=True, verbose_name='SPSS code')),
                ('child_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of', related_query_name='Parent of', to='geo.location', verbose_name='Child of')),
            ],
            options={
                'verbose_name': 'Geographic Location',
                'verbose_name_plural': 'Geographic Locations',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Geographic Location Type')),
            ],
            options={
                'verbose_name': 'Geographic Location Type',
                'verbose_name_plural': 'Geographic Location Types',
            },
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.JSONField(null=True, verbose_name='Geojson Polygon')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.IntegerField(null=True, verbose_name='Dataset')),
                ('shortest_route', models.JSONField(null=True, verbose_name='Endpoint to endpoint route')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceofroute', to='geo.location', verbose_name='Alice')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetofroute', to='geo.location', verbose_name='Bob')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_location', to='geo.locationtype', verbose_name='Location Type'),
        ),
        migrations.AddField(
            model_name='location',
            name='spatial_extent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.polygon', verbose_name='Polygon'),
        ),
        migrations.CreateModel(
            name='Adjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.IntegerField(null=True, verbose_name='Dataset')),
                ('distance', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Distance')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceof', to='geo.location', verbose_name='Alice')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetof', to='geo.location', verbose_name='Bob')),
            ],
            options={
                'verbose_name': 'Location Adjacency',
                'verbose_name_plural': 'Location Adjacencies',
            },
        ),
    ]
