# Generated by Django 4.2.1 on 2023-06-27 18:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='spatial_extent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.polygon', verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='shape',
            field=models.JSONField(blank=True, null=True, verbose_name='Geojson Polygon'),
        ),
    ]
