# Generated by Django 4.2.1 on 2023-06-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_polygon_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='spatial_extent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.polygon', verbose_name='Polygon'),
        ),
    ]
