# Generated by Django 4.2.1 on 2023-10-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_location_child_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='child_of',
            new_name='parent',
        ),
    ]
