<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-09-07 21:24
=======
# Generated by Django 4.2.1 on 2023-09-07 15:59
>>>>>>> hooper_admin_updates_sept7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_location_uuid_alter_location_spatial_extent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='child_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of', to='geo.location', verbose_name='Child of'),
        ),
    ]
