# Generated by Django 4.2.1 on 2024-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedquery',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='savedquery',
            name='is_legacy',
        ),
        migrations.AddField(
            model_name='savedquery',
            name='endpoint',
            field=models.CharField(choices=[('assessment', 'assessment'), ('past/enslaved', 'past/enslaved'), ('past/enslaver', 'past/enslaver'), ('voyage', 'voyage')], default='voyage', max_length=50),
        ),
        migrations.AddField(
            model_name='savedquery',
            name='hash_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='query',
            field=models.JSONField(),
        ),
    ]
