# Generated by Django 4.2.1 on 2023-08-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_sparsedate_day_alter_sparsedate_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparsedate',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
    ]
