# Generated by Django 4.2.1 on 2023-08-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_sparsedate_is_legacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparsedate',
            name='is_legacy',
        ),
    ]
