# Generated by Django 4.2.1 on 2023-08-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_sparsedate_is_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparsedate',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
    ]
