# Generated by Django 4.2 on 2023-04-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc_title', models.CharField(blank=True, max_length=150, null=True)),
                ('pub_year', models.IntegerField(blank=True, null=True)),
                ('zotero_uri', models.URLField(max_length=500)),
                ('full_ref', models.CharField(max_length=1000)),
                ('uid', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Source Authority',
                'verbose_name_plural': 'Source Authorities',
            },
        ),
        migrations.CreateModel(
            name='DocTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Document Tag',
                'verbose_name_plural': 'Document Tags',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iiif_manifest_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('zotero_uri', models.URLField(max_length=500)),
                ('text_ref', models.CharField(blank=True, max_length=255)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_refs', to='doc.doc')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
        migrations.AddField(
            model_name='doc',
            name='tags',
            field=models.ManyToManyField(to='doc.doctag'),
        ),
    ]
