# Generated by Django 4.2 on 2023-04-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctag',
            name='tag',
        ),
    ]
