# Generated by Django 4.0.2 on 2022-10-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_alter_doc_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='pub_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='tag',
            field=models.ManyToManyField(to='docs.DocTags'),
        ),
    ]
