# Generated by Django 4.2.1 on 2024-01-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaved',
            name='height',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Height in inches'),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='languagegroup',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Latitude of point'),
        ),
        migrations.AlterField(
            model_name='languagegroup',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Longitude of point'),
        ),
        migrations.AlterField(
            model_name='moderncountry',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude of Country'),
        ),
        migrations.AlterField(
            model_name='moderncountry',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude of Country'),
        ),
    ]
