# Generated by Django 4.2.1 on 2024-04-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0004_alter_enslaved_documented_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaved',
            name='enslaved_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
