# Generated by Django 4.2.1 on 2024-06-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0005_alter_enslaved_enslaved_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaveridentity',
            name='number_enslaved_people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
