# Generated by Django 4.2.1 on 2025-04-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0006_enslaveridentity_number_enslaved_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Gender',
            },
        ),
        migrations.RenameField(
            model_name='enslaved',
            old_name='gender',
            new_name='gender_int',
        ),
    ]
