# Generated by Django 4.2.1 on 2025-04-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0007_gender_rename_gender_enslaved_gender_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaved',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.gender'),
        ),
    ]
