# Generated by Django 4.2.1 on 2025-08-14 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0008_enslaved_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='roles',
            field=models.ManyToManyField(db_index=True, help_text='The role(s) of the enslaver in this relation', to='past.enslaverrole'),
        ),
        migrations.CreateModel(
            name='EnslaverRelatedDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ManyToManyField(to='past.enslaverrole')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='related_data_cache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.enslaverrelateddatacache'),
        ),
    ]
