# Generated by Django 4.2.1 on 2025-08-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0007_remove_linkedvoyages_mode'),
        ('past', '0009_alter_enslaverinrelation_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaverrelateddatacache',
            name='voyages',
            field=models.ManyToManyField(to='voyage.voyage'),
        ),
    ]
