# Generated by Django 4.2.1 on 2025-08-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0007_remove_linkedvoyages_mode'),
        ('past', '0010_enslaverrelateddatacache_voyages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enslaveridentity',
            name='related_data_cache',
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='roles',
            field=models.ManyToManyField(to='past.enslaverrole'),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='voyages',
            field=models.ManyToManyField(to='voyage.voyage'),
        ),
        migrations.DeleteModel(
            name='EnslaverRelatedDataCache',
        ),
    ]
