# Generated by Django 4.2.1 on 2025-08-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0007_remove_linkedvoyages_mode'),
        ('past', '0011_remove_enslaveridentity_related_data_cache_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaveridentity',
            name='roles',
            field=models.ManyToManyField(db_index=True, to='past.enslaverrole'),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='voyages',
            field=models.ManyToManyField(db_index=True, to='voyage.voyage'),
        ),
    ]
