# Generated by Django 4.2.1 on 2024-03-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_savedquery_hash_remove_savedquery_is_legacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquery',
            name='front_end_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
