# Generated by Django 4.2 on 2023-04-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportArea',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.place')),
                ('order_num', models.IntegerField()),
                ('show_at_zoom', models.IntegerField()),
                ('show_on_map', models.BooleanField()),
            ],
            bases=('geo.place',),
        ),
        migrations.CreateModel(
            name='ImportArea',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.place')),
                ('order_num', models.IntegerField()),
                ('show_at_zoom', models.IntegerField()),
                ('show_on_map', models.BooleanField()),
            ],
            bases=('geo.place',),
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.place')),
                ('order_num', models.IntegerField()),
            ],
            bases=('geo.place',),
        ),
        migrations.CreateModel(
            name='ImportRegion',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.place')),
                ('order_num', models.IntegerField()),
                ('show_at_zoom', models.IntegerField()),
                ('show_on_map', models.BooleanField()),
                ('import_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.importarea')),
            ],
            bases=('geo.place',),
        ),
        migrations.CreateModel(
            name='ExportRegion',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geo.place')),
                ('order_num', models.IntegerField()),
                ('show_at_zoom', models.IntegerField()),
                ('show_on_map', models.BooleanField()),
                ('export_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.exportarea')),
            ],
            bases=('geo.place',),
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('embarked_slaves', models.FloatField(blank=True, null=True)),
                ('disembarked_slaves', models.FloatField(blank=True, null=True)),
                ('disembarkation_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.importregion')),
                ('embarkation_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.exportregion')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.nation')),
            ],
        ),
    ]
