# Generated by Django 4.2 on 2023-04-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc_title', models.CharField(blank=True, max_length=150, null=True)),
                ('pub_year', models.IntegerField(blank=True, null=True)),
                ('zotero_uri', models.URLField(max_length=500)),
                ('full_ref', models.CharField(max_length=1000)),
                ('uid', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Source Authority',
                'verbose_name_plural': 'Source Authorities',
            },
        ),
        migrations.CreateModel(
            name='DocTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Document Tag',
                'verbose_name_plural': 'Document Tags',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iiif_manifest_uri', models.URLField(blank=True, max_length=500, null=True)),
                ('zotero_uri', models.URLField(max_length=500)),
                ('text_ref', models.CharField(blank=True, max_length=255)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_refs', to='assessment.doc')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
        migrations.RemoveField(
            model_name='exportarea',
            name='place_ptr',
        ),
        migrations.RemoveField(
            model_name='exportregion',
            name='export_area',
        ),
        migrations.RemoveField(
            model_name='exportregion',
            name='place_ptr',
        ),
        migrations.RemoveField(
            model_name='importarea',
            name='place_ptr',
        ),
        migrations.RemoveField(
            model_name='importregion',
            name='import_area',
        ),
        migrations.RemoveField(
            model_name='importregion',
            name='place_ptr',
        ),
        migrations.RemoveField(
            model_name='nation',
            name='place_ptr',
        ),
        migrations.DeleteModel(
            name='Estimate',
        ),
        migrations.DeleteModel(
            name='ExportArea',
        ),
        migrations.DeleteModel(
            name='ExportRegion',
        ),
        migrations.DeleteModel(
            name='ImportArea',
        ),
        migrations.DeleteModel(
            name='ImportRegion',
        ),
        migrations.DeleteModel(
            name='Nation',
        ),
        migrations.AddField(
            model_name='doc',
            name='tags',
            field=models.ManyToManyField(to='assessment.doctag'),
        ),
    ]
