# Generated by Django 4.2.1 on 2023-11-03 21:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptiveFate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaptiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Captive status',
                'verbose_name_plural': 'Captive statuses',
            },
        ),
        migrations.CreateModel(
            name='Enslaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enslaved_id', models.IntegerField(unique=True)),
                ('documented_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_first', models.CharField(blank=True, max_length=100, null=True)),
                ('name_second', models.CharField(blank=True, max_length=100, null=True)),
                ('name_third', models.CharField(blank=True, max_length=100, null=True)),
                ('modern_name', models.CharField(blank=True, max_length=100, null=True)),
                ('editor_modern_names_certainty', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, db_index=True, null=True)),
                ('gender', models.IntegerField(blank=True, db_index=True, null=True)),
                ('height', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True, verbose_name='Height in inches')),
                ('skin_color', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('dataset', models.IntegerField(blank=True, db_index=True, default=0, null=True)),
                ('notes', models.CharField(blank=True, max_length=8192, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('human_reviewed', models.BooleanField(blank=True, default=False, null=True)),
                ('captive_fate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.captivefate')),
                ('captive_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.captivestatus')),
            ],
            options={
                'verbose_name_plural': 'Enslaved People',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EnslavedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=3)),
                ('recordings_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnslavementRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, help_text='Date in MM,DD,YYYY format with optional fields.', max_length=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_from_voyages', models.BooleanField(blank=True, default=False, null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.location')),
            ],
        ),
        migrations.CreateModel(
            name='EnslavementRelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnslaverAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('manual_id', models.CharField(max_length=30, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('human_reviewed', models.BooleanField(blank=True, default=False, null=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enslaver alias',
                'verbose_name_plural': 'Enslaver aliases',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EnslaverRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, null=True, verbose_name='Longitude of point')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, null=True, verbose_name='Latitude of point')),
                ('shape', models.JSONField(blank=True, null=True, verbose_name='Geojson Polygon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PASTSparseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
            ],
            options={
                'ordering': ['year', 'month', 'day'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Register country',
                'verbose_name_plural': 'Register countries',
            },
        ),
        migrations.CreateModel(
            name='ModernCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude of Country')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude of Country')),
                ('shape', models.JSONField(blank=True, null=True, verbose_name='Geojson Polygon')),
                ('languages', models.ManyToManyField(to='past.languagegroup')),
            ],
            options={
                'verbose_name': 'Modern country',
                'verbose_name_plural': 'Modern countries',
            },
        ),
        migrations.CreateModel(
            name='EnslaverInRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enslaver_alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaver_relations', to='past.enslaveralias')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_enslavers', to='past.enslavementrelation')),
                ('roles', models.ManyToManyField(help_text='The role(s) of the enslaver in this relation', to='past.enslaverrole')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EnslaverIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_alias', models.CharField(max_length=255)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('birth_month', models.IntegerField(blank=True, null=True)),
                ('birth_day', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('death_month', models.IntegerField(blank=True, null=True)),
                ('death_day', models.IntegerField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('probate_date', models.CharField(blank=True, max_length=12, null=True)),
                ('will_value_pounds', models.CharField(blank=True, max_length=12, null=True)),
                ('will_value_dollars', models.CharField(blank=True, max_length=12, null=True)),
                ('will_court', models.CharField(blank=True, max_length=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=8192, null=True)),
                ('is_natural_person', models.BooleanField(blank=True, default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('human_reviewed', models.BooleanField(blank=True, default=False, null=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('birth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.location')),
                ('death_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.location')),
                ('principal_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.location')),
            ],
            options={
                'verbose_name': 'Enslaver Identity',
                'verbose_name_plural': 'Enslaver Identities',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='enslaveralias',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='past.enslaveridentity'),
        ),
        migrations.CreateModel(
            name='EnslavementRelationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)])),
                ('enslavement_relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='past.enslavementrelation')),
            ],
            options={
                'ordering': ['year', 'month', 'day'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enslavementrelation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='past.enslavementrelationtype'),
        ),
        migrations.AddField(
            model_name='enslavementrelation',
            name='voyage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyage_enslavement_relations', to='voyage.voyage'),
        ),
        migrations.CreateModel(
            name='EnslavedInRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enslaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_relations', to='past.enslaved')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_in_relation', to='past.enslavementrelation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='enslaved',
            name='language_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.languagegroup'),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='last_known_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='past.pastsparsedate', verbose_name='Last known date'),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='post_disembark_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.location'),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='register_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.registercountry'),
        ),
        migrations.CreateModel(
            name='AltLanguageGroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('language_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_names', to='past.languagegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
