# Generated by Django 4.2.1 on 2023-06-27 18:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_alter_africaninfo_id_alter_cargotype_id_and_more'),
        ('past', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enslaved',
            old_name='enslaved_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='languagegroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='moderncountry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='altlanguagegroupname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='captivefate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='captivestatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_enslaved_people', to='voyage.voyage'),
        ),
        migrations.AlterField(
            model_name='enslavedinrelation',
            name='enslaved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_relations', to='past.enslaved'),
        ),
        migrations.AlterField(
            model_name='enslavedinrelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_in_relation', to='past.enslavementrelation'),
        ),
        migrations.AlterField(
            model_name='enslavementrelationtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='enslaver_alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaver_relations', to='past.enslaveralias'),
        ),
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_enslavers', to='past.enslavementrelation'),
        ),
        migrations.AlterField(
            model_name='enslaverrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enslavervoyageconnection',
            name='enslaver_alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaver_voyage_connection', to='past.enslaveralias'),
        ),
        migrations.AlterField(
            model_name='enslavervoyageconnection',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_enslaver_connection', to='voyage.voyage'),
        ),
        migrations.AlterField(
            model_name='languagegroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moderncountry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registercountry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='EnslaverCachedProperties',
        ),
    ]
