# Generated by Django 4.2.1 on 2023-11-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enslavementrelationdate',
            options={'ordering': ['year', 'month', 'day']},
        ),
        migrations.AlterModelOptions(
            name='pastsparsedate',
            options={'ordering': ['year', 'month', 'day']},
        ),
        migrations.RemoveField(
            model_name='enslavementrelation',
            name='enslaved_in_relation',
        ),
        migrations.AddField(
            model_name='enslaved',
            name='enslaved_relations',
            field=models.ManyToManyField(related_name='enslaved_in_relation', to='past.enslavementrelation'),
        ),
    ]
