# Generated by Django 4.2.1 on 2023-10-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaveralias',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enslaveridentity',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
