# Generated by Django 4.2.1 on 2023-10-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0002_enslaveralias_legacy_id_enslaveridentity_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaved',
            name='enslaved_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
