# Generated by Django 4.2.1 on 2023-11-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0002_alter_enslavementrelationdate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enslaved',
            name='enslaved_relations',
        ),
        migrations.CreateModel(
            name='EnslavedInRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enslaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_relations', to='past.enslaved')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_in_relation', to='past.enslavementrelation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
