# Generated by Django 4.2.1 on 2023-06-12 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_remove_voyagesourcesconnection_zotero_source'),
        ('past', '0002_june_1_2023_johnconnor_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslavervoyageconnection',
            name='enslaver_alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaver_voyage_connection', to='past.enslaveralias'),
        ),
        migrations.AlterField(
            model_name='enslavervoyageconnection',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_enslaver_connection', to='voyage.voyage'),
        ),
    ]
