# Generated by Django 4.2.1 on 2023-10-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0003_enslaved_enslaved_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslavementrelation',
            name='enslaved_in_relation',
            field=models.ManyToManyField(related_name='enslaved_relations', to='past.enslaved'),
        ),
    ]
