# Generated by Django 4.2.1 on 2024-04-16 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0003_alter_enslavementrelationdate_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaved',
            name='documented_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='editor_modern_names_certainty',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='modern_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='name_first',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='name_second',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='name_third',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslavedname',
            name='language',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='enslavedname',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='date',
            field=models.CharField(blank=True, db_index=True, help_text='Date in MM,DD,YYYY format with optional fields.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslavementrelationdate',
            name='day',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='enslavementrelationdate',
            name='month',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='enslavementrelationdate',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='enslaveralias',
            name='alias',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enslaveralias',
            name='manual_id',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='father_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='father_occupation',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='mother_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='principal_alias',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='probate_date',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_court',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_value_dollars',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_value_pounds',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pastsparsedate',
            name='day',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='pastsparsedate',
            name='month',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='pastsparsedate',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
