# Generated by Django 4.2.1 on 2023-06-30 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_voyage_human_reviewed'),
        ('past', '0004_enslaved_human_reviewed_enslaved_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaved',
            name='age',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='captive_fate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.captivefate'),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='captive_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.captivestatus'),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='dataset',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='documented_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='gender',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='height',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True, verbose_name='Height in inches'),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='language_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='past.languagegroup'),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='notes',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='post_disembark_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.place'),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='register_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='past.registercountry'),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='skin_color',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', through='past.EnslavedSourceConnection', to='voyage.voyagesources'),
        ),
        migrations.AlterField(
            model_name='enslaved',
            name='voyage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_enslaved_people', to='voyage.voyage'),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='birth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.place'),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='death_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='death_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='death_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.place'),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='is_natural_person',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='notes',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='principal_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voyage.place'),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='probate_date',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_court',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_value_dollars',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='will_value_pounds',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
