# Generated by Django 4.2.1 on 2023-06-12 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0004_alter_enslaverinrelation_enslaver_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslavedinrelation',
            name='enslaved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_relations', to='past.enslaved'),
        ),
        migrations.AlterField(
            model_name='enslavedinrelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_in_relation', to='past.enslavementrelation'),
        ),
    ]
