# Generated by Django 4.2.1 on 2023-06-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0005_alter_enslavedinrelation_enslaved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='enslaver_alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaver_relations', to='past.enslaveralias'),
        ),
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_enslavers', to='past.enslavementrelation'),
        ),
    ]
