# Generated by Django 4.2.1 on 2023-06-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0006_alter_enslaved_voyage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enslaved',
            options={'verbose_name_plural': 'Enslaved People'},
        ),
    ]
