# Generated by Django 4.2.1 on 2023-08-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0008_enslavementrelation_is_from_voyages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enslaved',
            options={'ordering': ['id'], 'verbose_name_plural': 'Enslaved People'},
        ),
        migrations.AlterModelOptions(
            name='enslavedinrelation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='enslavementrelation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='enslaveralias',
            options={'ordering': ['id'], 'verbose_name': 'Enslaver alias', 'verbose_name_plural': 'Enslaver aliases'},
        ),
        migrations.AlterModelOptions(
            name='enslaveridentity',
            options={'ordering': ['id'], 'verbose_name': 'Enslaver Identity', 'verbose_name_plural': 'Enslaver Identities'},
        ),
        migrations.AlterModelOptions(
            name='enslaverinrelation',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='enslavedinrelation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='enslaverinrelation',
            unique_together=set(),
        ),
    ]
