# Generated by Django 4.2.1 on 2023-09-07 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0008_alter_voyageitinerary_broad_region_of_return_and_more'),
        ('past', '0009_alter_enslaved_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaved',
            name='post_disembark_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.place'),
        ),
        migrations.AlterField(
            model_name='enslaveridentity',
            name='principal_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voyage.place'),
        ),
    ]
