# Generated by Django 4.2.1 on 2023-09-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0009_alter_enslaved_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslavervoyageconnection',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
