# Generated by Django 4.2.1 on 2023-09-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0006_alter_voyagedates_arrival_at_second_place_landing_sparsedate_and_more'),
        ('past', '0009_alter_enslaved_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslavementrelation',
            name='voyage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_enslavement_relations', to='voyage.voyage'),
        ),
    ]
