# Generated by Django 4.2.1 on 2023-09-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0007_alter_voyagedates_arrival_at_second_place_landing_sparsedate_and_more'),
        ('past', '0010_alter_enslavervoyageconnection_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslavementrelation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='date',
            field=models.CharField(blank=True, help_text='Date in MM,DD,YYYY format with optional fields.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='is_from_voyages',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.place'),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.voyagesources'),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='unnamed_enslaved_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='voyage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.voyage'),
        ),
    ]
