# Generated by Django 4.2.1 on 2023-09-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0008_alter_voyageitinerary_broad_region_of_return_and_more'),
        ('past', '0010_alter_enslaved_post_disembark_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslavementrelation',
            name='relation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='past.enslavementrelationtype'),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='voyage.voyagesources'),
        ),
        migrations.AlterField(
            model_name='enslavementrelation',
            name='voyage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voyage_enslavement_relation', to='voyage.voyage'),
        ),
    ]
