# Generated by Django 4.2.1 on 2023-09-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0011_alter_enslavementrelation_relation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslavervoyageconnection',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
