# Generated by Django 4.2.1 on 2024-01-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_voyagecargoconnection_is_purchasing_commmodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagecargoconnection',
            name='amount',
            field=models.FloatField(null=True, verbose_name='The amount of cargo according to the unit'),
        ),
        migrations.AlterField(
            model_name='voyageship',
            name='tonnage_mod',
            field=models.FloatField(blank=True, null=True, verbose_name='Tonnage standardized on British measured tons, 1773-1870'),
        ),
        migrations.AlterField(
            model_name='voyageslavesnumbers',
            name='imp_jamaican_cash_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Sterling cash price in Jamaica* (imputed)'),
        ),
    ]
