# Generated by Django 4.2.1 on 2024-01-24 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_alter_voyagecargoconnection_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagesparsedate',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
