# Generated by Django 4.2.1 on 2024-04-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0004_alter_voyagesparsedate_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationality',
            name='value',
            field=models.IntegerField(unique=True),
        ),
    ]
