# Generated by Django 4.2.1 on 2025-03-09 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0006_alter_rigofvessel_name_alter_voyagegroupings_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedvoyages',
            name='mode',
        ),
    ]
