# Generated by Django 4.0 on 2022-03-17 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagecaptainconnection',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_captain', to='voyage.voyagecaptain'),
        ),
        migrations.AlterField(
            model_name='voyagecaptainconnection',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_voyage', to='voyage.voyage'),
        ),
    ]
