# Generated by Django 3.2.6 on 2022-01-31 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owneroutcome',
            options={'ordering': ['value'], 'verbose_name': 'Owner Outcome', 'verbose_name_plural': 'Owner Outcomes'},
        ),
        migrations.AlterModelOptions(
            name='resistance',
            options={'ordering': ['value'], 'verbose_name': 'Resistance', 'verbose_name_plural': 'Resistances'},
        ),
        migrations.AlterModelOptions(
            name='slavesoutcome',
            options={'ordering': ['value'], 'verbose_name': 'Captives Outcome', 'verbose_name_plural': "Captives' Outcomes"},
        ),
        migrations.AlterModelOptions(
            name='voyageshipowner',
            options={'verbose_name': 'Ship Owner', 'verbose_name_plural': 'Ship Owners'},
        ),
        migrations.AlterModelOptions(
            name='voyageslavesnumbers',
            options={'verbose_name': 'Numbers of Voyage Captives', 'verbose_name_plural': "Numbers of Voyages' Captives"},
        ),
        migrations.AlterModelManagers(
            name='voyage',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='voyagesourcesconnection',
            name='source_order',
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='arrival_at_second_place_landing_dd',
            field=models.CharField(blank=True, help_text='Day in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Day of arrival at second place of landing (DATARR37,36,38)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='arrival_at_second_place_landing_mm',
            field=models.CharField(blank=True, help_text='Month in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Month of arrival at second place of landing (DATARR37,36,38)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='arrival_at_second_place_landing_yyyy',
            field=models.CharField(blank=True, help_text='Year in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Year of arrival at second place of landing (DATARR37,36,38)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='date_departed_africa_dd',
            field=models.CharField(blank=True, help_text='Day in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Day vessel departed Africa (DATELEFTAFR)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='date_departed_africa_mm',
            field=models.CharField(blank=True, help_text='Month in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Month vessel departed Africa (DATELEFTAFR)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='date_departed_africa_yyyy',
            field=models.CharField(blank=True, help_text='Year in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Year vessel departed Africa (DATELEFTAFR)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='departure_last_place_of_landing_dd',
            field=models.CharField(blank=True, help_text='Day in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Day of departure from last place of landing (DDEPAMB,*,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='departure_last_place_of_landing_mm',
            field=models.CharField(blank=True, help_text='Month in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Month of departure from last place of landing (DDEPAMB,*,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='departure_last_place_of_landing_yyyy',
            field=models.CharField(blank=True, help_text='Year in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Year of departure from last place of landing (DDEPAMB,*,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='first_dis_of_slaves_dd',
            field=models.CharField(blank=True, help_text='Day in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Day of first disembarkation of slaves (DATARR33,32,34)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='first_dis_of_slaves_mm',
            field=models.CharField(blank=True, help_text='Month in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Month of first disembarkation of slaves (DATARR33,32,34)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='first_dis_of_slaves_yyyy',
            field=models.CharField(blank=True, help_text='Year in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Year of first disembarkation of slaves (DATARR33,32,34)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='imp_arrival_at_port_of_dis_yyyy',
            field=models.IntegerField(blank=True, help_text='Date in format: YYYY', null=True, verbose_name='Year of arrival at port of disembarkation (YEARAM)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='imp_departed_africa_yyyy',
            field=models.IntegerField(blank=True, help_text='Date in format: YYYY', null=True, verbose_name='Year departed Africa'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='imp_voyage_began_yyyy',
            field=models.CharField(blank=True, help_text='Date in format: YYYY', max_length=10, null=True, verbose_name='Year voyage began'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='slave_purchase_began_dd',
            field=models.CharField(blank=True, help_text='Day in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Day that slave purchase began (D1SLATRB,A,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='slave_purchase_began_mm',
            field=models.CharField(blank=True, help_text='Month in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Month that slave purchase began (D1SLATRB,A,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='slave_purchase_began_yyyy',
            field=models.CharField(blank=True, help_text='Year in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Year that slave purchase began (D1SLATRB,A,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='third_dis_of_slaves_dd',
            field=models.CharField(blank=True, help_text='Day in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Day of third disembarkation of slaves (DATARR40,39,41)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='third_dis_of_slaves_mm',
            field=models.CharField(blank=True, help_text='Month in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Month of third disembarkation of slaves (DATARR40,39,41)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='third_dis_of_slaves_yyyy',
            field=models.CharField(blank=True, help_text='Year in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Year of third disembarkation of slaves (DATARR40,39,41)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='vessel_left_port_dd',
            field=models.CharField(blank=True, help_text='Day in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Day that vessel left last slaving port (DLSLATRB,A,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='vessel_left_port_mm',
            field=models.CharField(blank=True, help_text='Month in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Month that vessel left last slaving port (DLSLATRB,A,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='vessel_left_port_yyyy',
            field=models.CharField(blank=True, help_text='Year in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Year that vessel left last slaving port (DLSLATRB,A,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='voyage_began_dd',
            field=models.CharField(blank=True, help_text='Day in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Day that voyage began (DATEDEPB,A,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='voyage_began_mm',
            field=models.CharField(blank=True, help_text='Month in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Month that voyage began (DATEDEPB,A,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='voyage_began_yyyy',
            field=models.CharField(blank=True, help_text='Year in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Year that voyage began (DATEDEPB,A,C)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='voyage_completed_dd',
            field=models.CharField(blank=True, help_text='Day in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Day on which slave voyage completed (DATARR44,43,45)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='voyage_completed_mm',
            field=models.CharField(blank=True, help_text='Month in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Month on which slave voyage completed (DATARR44,43,45)'),
        ),
        migrations.AddField(
            model_name='voyagedates',
            name='voyage_completed_yyyy',
            field=models.CharField(blank=True, help_text='Year in format: MM,DD,YYYY', max_length=10, null=True, verbose_name='Year on which slave voyage completed (DATARR44,43,45)'),
        ),
        migrations.AlterField(
            model_name='region',
            name='broad_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.broadregion', verbose_name='Broad Region'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_crew', to='voyage.voyagecrew', verbose_name='Crew'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_dates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_dates', to='voyage.voyagedates', verbose_name='Dates'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_groupings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voyage.voyagegroupings', verbose_name='Voyage Groupings'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_itinerary', to='voyage.voyageitinerary', verbose_name='Itinerary'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_ship', to='voyage.voyageship', verbose_name='Ship'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='voyage_sources',
            field=models.ManyToManyField(blank=True, related_name='sources', through='voyage.VoyageSourcesConnection', to='voyage.VoyageSources'),
        ),
        migrations.AlterField(
            model_name='voyageoutcome',
            name='voyage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_outcomes', to='voyage.voyage'),
        ),
        migrations.AlterField(
            model_name='voyageship',
            name='imputed_nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imputed_nationality', to='voyage.nationality', verbose_name='Imputed Ship Nationality'),
        ),
        migrations.AlterField(
            model_name='voyageship',
            name='nationality_ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nationality_ship', to='voyage.nationality', verbose_name='Ship Nationality'),
        ),
        migrations.AlterField(
            model_name='voyageship',
            name='rig_of_vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voyage.rigofvessel', verbose_name='Rig of Vessel'),
        ),
        migrations.AlterField(
            model_name='voyageship',
            name='ton_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voyage.tontype', verbose_name='Type of Tonnage'),
        ),
        migrations.AlterField(
            model_name='voyageship',
            name='tonnage_mod',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Tonnage standardized on British measured tons 1773-1870'),
        ),
        migrations.AlterField(
            model_name='voyageshipownerconnection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to='voyage.voyageshipowner', verbose_name='Ship Owner'),
        ),
        migrations.AlterField(
            model_name='voyageslavesnumbers',
            name='total_slaves_embarked_age_gender_identified',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total slaves embarked wi th age and gender identified (SLAVMAX1)'),
        ),
        migrations.AlterField(
            model_name='voyagesources',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.voyagesourcestype', verbose_name='Source Type'),
        ),
        migrations.AlterField(
            model_name='voyagesourcesconnection',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_groups', to='voyage.voyage'),
        ),
        migrations.AlterField(
            model_name='voyagesourcesconnection',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_sources', to='voyage.voyagesources'),
        ),
    ]
