# Generated by Django 4.0 on 2022-03-17 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_alter_voyagecaptainconnection_captain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagecaptainconnection',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.voyagecaptain'),
        ),
        migrations.AlterField(
            model_name='voyagecaptainconnection',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_captainconnection', to='voyage.voyage'),
        ),
        migrations.AlterField(
            model_name='voyageshipownerconnection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.voyageshipowner', verbose_name='Ship Owner'),
        ),
        migrations.AlterField(
            model_name='voyageshipownerconnection',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_shipownerconnection', to='voyage.voyage'),
        ),
        migrations.AlterField(
            model_name='voyagesourcesconnection',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.voyagesources'),
        ),
        migrations.AlterField(
            model_name='voyagesourcesconnection',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_sourceconnection', to='voyage.voyage'),
        ),
    ]
