# Generated by Django 3.2.6 on 2022-01-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0002_auto_20220131_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyagedates',
            name='arrival_at_second_place_landing_dd',
            field=models.IntegerField(blank=True, help_text='Day in format: MM,DD,YYYY', null=True, verbose_name='Day of arrival at second place of landing (DATARR37,36,38)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='arrival_at_second_place_landing_mm',
            field=models.IntegerField(blank=True, help_text='Month in format: MM,DD,YYYY', null=True, verbose_name='Month of arrival at second place of landing (DATARR37,36,38)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='arrival_at_second_place_landing_yyyy',
            field=models.IntegerField(blank=True, help_text='Year in format: MM,DD,YYYY', null=True, verbose_name='Year of arrival at second place of landing (DATARR37,36,38)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='date_departed_africa_dd',
            field=models.IntegerField(blank=True, help_text='Day in format: MM,DD,YYYY', null=True, verbose_name='Day vessel departed Africa (DATELEFTAFR)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='date_departed_africa_mm',
            field=models.IntegerField(blank=True, help_text='Month in format: MM,DD,YYYY', null=True, verbose_name='Month vessel departed Africa (DATELEFTAFR)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='date_departed_africa_yyyy',
            field=models.IntegerField(blank=True, help_text='Year in format: MM,DD,YYYY', null=True, verbose_name='Year vessel departed Africa (DATELEFTAFR)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='departure_last_place_of_landing_dd',
            field=models.IntegerField(blank=True, help_text='Day in format: MM,DD,YYYY', null=True, verbose_name='Day of departure from last place of landing (DDEPAMB,*,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='departure_last_place_of_landing_mm',
            field=models.IntegerField(blank=True, help_text='Month in format: MM,DD,YYYY', null=True, verbose_name='Month of departure from last place of landing (DDEPAMB,*,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='departure_last_place_of_landing_yyyy',
            field=models.IntegerField(blank=True, help_text='Year in format: MM,DD,YYYY', null=True, verbose_name='Year of departure from last place of landing (DDEPAMB,*,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='first_dis_of_slaves_dd',
            field=models.IntegerField(blank=True, help_text='Day in format: MM,DD,YYYY', null=True, verbose_name='Day of first disembarkation of slaves (DATARR33,32,34)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='first_dis_of_slaves_mm',
            field=models.IntegerField(blank=True, help_text='Month in format: MM,DD,YYYY', null=True, verbose_name='Month of first disembarkation of slaves (DATARR33,32,34)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='first_dis_of_slaves_yyyy',
            field=models.IntegerField(blank=True, help_text='Year in format: MM,DD,YYYY', null=True, verbose_name='Year of first disembarkation of slaves (DATARR33,32,34)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='imp_voyage_began_yyyy',
            field=models.IntegerField(blank=True, help_text='Date in format: YYYY', null=True, verbose_name='Year voyage began'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='slave_purchase_began_dd',
            field=models.IntegerField(blank=True, help_text='Day in format: MM,DD,YYYY', null=True, verbose_name='Day that slave purchase began (D1SLATRB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='slave_purchase_began_mm',
            field=models.IntegerField(blank=True, help_text='Month in format: MM,DD,YYYY', null=True, verbose_name='Month that slave purchase began (D1SLATRB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='slave_purchase_began_yyyy',
            field=models.IntegerField(blank=True, help_text='Year in format: MM,DD,YYYY', null=True, verbose_name='Year that slave purchase began (D1SLATRB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='third_dis_of_slaves_dd',
            field=models.IntegerField(blank=True, help_text='Day in format: MM,DD,YYYY', null=True, verbose_name='Day of third disembarkation of slaves (DATARR40,39,41)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='third_dis_of_slaves_mm',
            field=models.IntegerField(blank=True, help_text='Month in format: MM,DD,YYYY', null=True, verbose_name='Month of third disembarkation of slaves (DATARR40,39,41)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='third_dis_of_slaves_yyyy',
            field=models.IntegerField(blank=True, help_text='Year in format: MM,DD,YYYY', null=True, verbose_name='Year of third disembarkation of slaves (DATARR40,39,41)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='vessel_left_port_dd',
            field=models.IntegerField(blank=True, help_text='Day in format: MM,DD,YYYY', null=True, verbose_name='Day that vessel left last slaving port (DLSLATRB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='vessel_left_port_mm',
            field=models.IntegerField(blank=True, help_text='Month in format: MM,DD,YYYY', null=True, verbose_name='Month that vessel left last slaving port (DLSLATRB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='vessel_left_port_yyyy',
            field=models.IntegerField(blank=True, help_text='Year in format: MM,DD,YYYY', null=True, verbose_name='Year that vessel left last slaving port (DLSLATRB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='voyage_began_dd',
            field=models.IntegerField(blank=True, help_text='Day in format: MM,DD,YYYY', null=True, verbose_name='Day that voyage began (DATEDEPB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='voyage_began_mm',
            field=models.IntegerField(blank=True, help_text='Month in format: MM,DD,YYYY', null=True, verbose_name='Month that voyage began (DATEDEPB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='voyage_began_yyyy',
            field=models.IntegerField(blank=True, help_text='Year in format: MM,DD,YYYY', null=True, verbose_name='Year that voyage began (DATEDEPB,A,C)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='voyage_completed_dd',
            field=models.IntegerField(blank=True, help_text='Day in format: MM,DD,YYYY', null=True, verbose_name='Day on which slave voyage completed (DATARR44,43,45)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='voyage_completed_mm',
            field=models.IntegerField(blank=True, help_text='Month in format: MM,DD,YYYY', null=True, verbose_name='Month on which slave voyage completed (DATARR44,43,45)'),
        ),
        migrations.AlterField(
            model_name='voyagedates',
            name='voyage_completed_yyyy',
            field=models.IntegerField(blank=True, help_text='Year in format: MM,DD,YYYY', null=True, verbose_name='Year on which slave voyage completed (DATARR44,43,45)'),
        ),
    ]
