# Generated by Django 4.0.2 on 2022-04-11 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_alter_voyagecaptainconnection_captain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoyageAnimationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_dump', models.CharField(max_length=255, verbose_name='json_dump')),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='voyage_animation_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voyage.voyageanimationindex'),
        ),
    ]
