# Generated by Django 3.2.6 on 2022-03-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_auto_20220131_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationality',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owneroutcome',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='particularoutcome',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resistance',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rigofvessel',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='slavesoutcome',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tontype',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vesselcapturedoutcome',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='voyagegroupings',
            old_name='label',
            new_name='name',
        ),
    ]
