# Generated by Django 4.0.2 on 2022-05-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0003_alter_voyagecaptainconnection_captain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voyage.region', verbose_name='Region'),
        ),
    ]
