# Generated by Django 3.2.6 on 2022-03-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0004_auto_20220304_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vesselcapturedoutcome',
            options={'ordering': ['value'], 'verbose_name': 'Vessel Captured Outcome', 'verbose_name_plural': 'Vessel Captured Outcomes'},
        ),
        migrations.AlterModelOptions(
            name='voyagecaptain',
            options={'verbose_name': 'Captain', 'verbose_name_plural': 'Captains'},
        ),
    ]
