# Generated by Django 4.0.2 on 2022-05-31 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_alter_location_child_of'),
        ('voyage', '0004_alter_place_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadregion',
            name='geo_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='place',
            name='geo_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='region',
            name='geo_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.location', verbose_name='Location'),
        ),
    ]
