# Generated by Django 4.0.2 on 2022-06-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0007_remove_place_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='region',
        ),
        migrations.RemoveField(
            model_name='place',
            name='show_on_main_map',
        ),
        migrations.RemoveField(
            model_name='place',
            name='show_on_voyage_map',
        ),
        migrations.RemoveField(
            model_name='place',
            name='value',
        ),
    ]
