# Generated by Django 4.0.2 on 2022-07-26 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0009_alter_broadregion_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfricanInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('possibly_offensive', models.BooleanField(default=False, help_text='Indicates that the wording used in this label might be offensive to readers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargoUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoyageCargoConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True, verbose_name='The amount of cargo according to the unit')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.cargotype')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.cargounit')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voyage.voyage')),
            ],
            options={
                'unique_together': {('voyage', 'cargo')},
            },
        ),
    ]
