# Generated by Django 4.0.2 on 2022-07-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0010_africaninfo_cargotype_cargounit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='african_info',
            field=models.ManyToManyField(blank=True, related_name='african_info', to='voyage.AfricanInfo'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='cargo',
            field=models.ManyToManyField(blank=True, through='voyage.VoyageCargoConnection', to='voyage.CargoType'),
        ),
    ]
