# Generated by Django 4.2.1 on 2023-06-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_doctest'),
        ('voyage', '0002_june_1_2023_johnconnor_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagesourcesconnection',
            name='zotero_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='z_voys_cnx', to='document.zoterosource'),
        ),
    ]
