# Generated by Django 4.0.2 on 2022-06-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0006_alter_place_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place',
        ),
    ]
