# Generated by Django 4.0.2 on 2022-06-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0008_remove_place_latitude_remove_place_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadregion',
            options={'verbose_name': 'Broad region (area)', 'verbose_name_plural': 'Broad regions (areas)'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.RemoveField(
            model_name='broadregion',
            name='broad_region',
        ),
        migrations.RemoveField(
            model_name='broadregion',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='broadregion',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='broadregion',
            name='show_on_map',
        ),
        migrations.RemoveField(
            model_name='broadregion',
            name='value',
        ),
        migrations.RemoveField(
            model_name='region',
            name='broad_region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='region',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='region',
            name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='show_on_main_map',
        ),
        migrations.RemoveField(
            model_name='region',
            name='show_on_map',
        ),
        migrations.RemoveField(
            model_name='region',
            name='value',
        ),
    ]
