# Generated by Django 4.0.2 on 2022-07-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_remove_doc_source'),
        ('voyage', '0011_voyage_african_info_voyage_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyagesourcesconnection',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.doc'),
        ),
    ]
