# Generated by Django 4.2.1 on 2023-06-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_zoterosource_zotero_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcepage',
            name='iiif_baseimage_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sourcepage',
            name='iiif_manifest_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='zoterosource',
            name='zotero_url',
            field=models.URLField(max_length=400, unique=True),
        ),
    ]
