# Generated by Django 4.2.1 on 2023-06-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_zoterosource_legacy_source_zoterosource_source_cnx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zoterosource',
            unique_together={('zotero_title', 'zotero_date')},
        ),
    ]
