# Generated by Django 4.2.1 on 2023-06-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_remove_voyagesourcesconnection_zotero_source'),
        ('document', '0006_alter_zoterosource_zotero_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoterosource',
            name='source_cnx',
        ),
        migrations.AddField(
            model_name='zoterosource',
            name='source_cnx',
            field=models.ManyToManyField(null=True, related_name='sourcecnx_zotero_refs', to='voyage.voyagesourcesconnection'),
        ),
    ]
