# Generated by Django 4.2.1 on 2023-06-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_remove_voyagesourcesconnection_zotero_source'),
        ('document', '0009_alter_zoterosource_enslaved_people_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zoterosource',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='zoterosource',
            name='zotero_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='zoterosource',
            unique_together={('zotero_title', 'zotero_url', 'legacy_source')},
        ),
    ]
