# Generated by Django 4.2.1 on 2023-06-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_alter_zoterosource_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcepage',
            name='item_url',
        ),
        migrations.AddField(
            model_name='sourcepage',
            name='page_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='zoterosource',
            name='page_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
