# Generated by Django 4.2.1 on 2023-06-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_remove_sourcepage_item_url_sourcepage_page_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoterosource',
            name='page_url',
        ),
        migrations.AddField(
            model_name='zoterosource',
            name='item_url',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sourcepage',
            name='page_url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
