# Generated by Django 4.0.2 on 2022-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='shape',
            field=models.JSONField(null=True, verbose_name='Geojson Polygon'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_linestring',
            field=models.JSONField(null=True, verbose_name='Geojson Linestring'),
        ),
    ]
