# Generated by Django 4.0.2 on 2022-05-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_alter_location_child_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='child_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of', related_query_name='Parent of', to='geo.location', verbose_name='Child of'),
        ),
    ]
