# Generated by Django 4.0.2 on 2022-07-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0013_remove_adjacency_shortest_route_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjacency',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Distance'),
        ),
    ]
