# Generated by Django 3.2.6 on 2022-01-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaved',
            name='last_known_date_dd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='last_known_date_mm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslaved',
            name='last_known_year_yyyy',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslavementrelation',
            name='date_dd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslavementrelation',
            name='date_mm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enslavementrelation',
            name='date_yyyy',
            field=models.IntegerField(null=True),
        ),
    ]
