# Generated by Django 4.0.2 on 2022-07-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0002_alter_enslaveralias_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslavervoyageconnection',
            name='enslaver_alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaver_voyage', to='past.enslaveralias'),
        ),
    ]
