# Generated by Django 3.2.6 on 2022-02-01 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0002_auto_20220131_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='enslaved',
            name='id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='enslaverinrelation',
            name='enslaver_alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='past.enslaveralias'),
        ),
    ]
