# Generated by Django 4.0.2 on 2022-07-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0003_alter_enslavervoyageconnection_enslaver_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='external_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('enslaved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enslaved_bio', to='past.enslaved')),
                ('enslaver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enslaver_bio', to='past.enslaveridentity')),
            ],
        ),
    ]
