# Generated by Django 3.2.6 on 2022-02-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0004_auto_20220201_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enslavementrelation',
            name='relation_type',
        ),
    ]
