# Generated by Django 3.2.6 on 2022-02-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0005_remove_enslavementrelation_relation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnslavementRelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='enslavementrelation',
            name='relation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='past.enslavementrelationtype'),
        ),
    ]
