# Generated by Django 3.2.6 on 2022-02-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0006_auto_20220201_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enslaverinrelation',
            name='role',
        ),
    ]
