# Generated by Django 3.2.6 on 2022-02-01 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0007_remove_enslaverinrelation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnslaverRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='enslaverinrelation',
            name='role',
            field=models.ForeignKey(help_text='The role of the enslaver in this relation', null=True, on_delete=django.db.models.deletion.CASCADE, to='past.enslaverrole'),
        ),
    ]
