# Generated by Django 3.2.6 on 2022-02-01 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0012_auto_20220201_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enslaveridentitysourceconnection',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaver_sources', to='past.enslaveridentity'),
        ),
    ]
