# Generated by Django 3.2.6 on 2022-03-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0013_alter_enslaveridentitysourceconnection_identity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enslaved',
            old_name='enslaved_id',
            new_name='id',
        ),
    ]
