# Generated by Django 4.2.1 on 2023-06-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voyage', '0001_initial'),
        ('past', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(max_length=400, null=True)),
                ('iiif_manifest_url', models.URLField(blank=True, max_length=400, null=True)),
                ('iiif_baseimage_url', models.URLField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoteroSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_url', models.URLField(max_length=400, null=True)),
                ('zotero_url', models.URLField(max_length=400)),
                ('zotero_title', models.CharField(max_length=255)),
                ('zotero_date', models.CharField(max_length=60)),
                ('enslaved_people', models.ManyToManyField(related_name='enslaved_zoterorefs', to='past.enslaved')),
                ('enslavers', models.ManyToManyField(related_name='enslaver_zoterorefs', to='past.enslaveridentity')),
                ('legacy_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_zotero_refs', to='voyage.voyagesources')),
                ('voyages', models.ManyToManyField(related_name='voyage_zoterorefs', to='voyage.voyage')),
            ],
            options={
                'unique_together': {('zotero_title', 'zotero_url', 'legacy_source')},
            },
        ),
        migrations.CreateModel(
            name='SourcePageConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zotero_connection', to='document.sourcepage')),
                ('zotero_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_connection', to='document.zoterosource')),
            ],
            options={
                'unique_together': {('zotero_source', 'source_page')},
            },
        ),
    ]
