# Generated by Django 4.2.1 on 2023-06-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourcePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_url', models.URLField(blank=True, null=True)),
                ('iiif_manifest_url', models.URLField(blank=True, null=True)),
                ('iiif_baseimage_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoteroSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zotero_url', models.URLField()),
                ('zotero_title', models.CharField(max_length=255)),
                ('zotero_date', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SourcePageConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zotero_connection', to='document.sourcepage')),
                ('zotero_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_connection', to='document.zoterosource')),
            ],
            options={
                'unique_together': {('zotero_source', 'source_page')},
            },
        ),
    ]
