# Generated by Django 4.2.1 on 2023-11-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
