# Generated by Django 4.2.1 on 2023-06-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_doctest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoterosource',
            name='zotero_title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='zoterosource',
            name='zotero_url',
            field=models.URLField(unique=True),
        ),
    ]
