# Generated by Django 4.2.1 on 2023-11-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docsparsedate',
            options={'ordering': ['year', 'month', 'day']},
        ),
    ]
