# Generated by Django 4.2.1 on 2023-10-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sourceenslavedconnection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sourceenslaverconnection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sourcepageconnection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sourcevoyageconnection',
            unique_together=set(),
        ),
    ]
