# Generated by Django 4.2.1 on 2023-10-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SourcePage',
            new_name='Page',
        ),
        migrations.RenameField(
            model_name='sourcepageconnection',
            old_name='source_page',
            new_name='page',
        ),
        migrations.AlterUniqueTogether(
            name='sourcepageconnection',
            unique_together={('source', 'page'), ('source', 'order')},
        ),
    ]
