# Generated by Django 4.2.1 on 2023-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_sourcepage_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcepage',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
