# Generated by Django 4.2.1 on 2023-11-14 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_source_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='short_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_ref_sources', to='document.shortref'),
        ),
    ]
