# Generated by Django 4.2.1 on 2023-11-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_docsparsedate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcepageconnection',
            name='order',
        ),
    ]
