# Generated by Django 4.2.1 on 2023-10-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_rename_sourcepage_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sourcepageconnection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='document.page'),
        ),
        migrations.AlterField(
            model_name='sourcepageconnection',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_connections', to='document.source'),
        ),
    ]
