# Generated by Django 4.2.1 on 2023-06-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_sourcepage_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcepage',
            name='human_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sourcepage',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='zoterosource',
            name='human_reviewed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='zoterosource',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
