# Generated by Django 4.2.1 on 2023-11-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_sourcepageconnection_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='iiif_baseimage_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
