# Generated by Django 4.2.1 on 2023-06-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_zoterosource_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoterosource',
            name='zotero_url',
            field=models.URLField(max_length=400),
        ),
    ]
