# Generated by Django 4.2.1 on 2024-01-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_page_is_british_library_page_transkribus_pageid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='bib',
            field=models.TextField(help_text='Formatted bibliography for the Document', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='thumbnail',
            field=models.TextField(help_text='URL for a thumbnail of the Document', null=True),
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('is_translation', models.BooleanField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='document.page')),
            ],
        ),
    ]
