# Generated by Django 4.2.1 on 2023-07-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_voyage_human_reviewed'),
        ('document', '0007_zoterovoyageconnection_page_range'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zoterovoyageconnection',
            unique_together={('zotero_source', 'voyage', 'page_range')},
        ),
    ]
