# Generated by Django 4.2.1 on 2023-06-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_remove_voyagesourcesconnection_zotero_source'),
        ('past', '0002_june_1_2023_johnconnor_api'),
        ('document', '0007_remove_zoterosource_source_cnx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoterosource',
            name='source_cnx',
        ),
        migrations.AddField(
            model_name='zoterosource',
            name='enslaved_people',
            field=models.ManyToManyField(null=True, related_name='enslaved_zoterorefs', to='past.enslaved'),
        ),
        migrations.AddField(
            model_name='zoterosource',
            name='enslavers',
            field=models.ManyToManyField(null=True, related_name='enslaver_zoterorefs', to='past.enslaveridentity'),
        ),
        migrations.AddField(
            model_name='zoterosource',
            name='voyages',
            field=models.ManyToManyField(null=True, related_name='voyage_zoterorefs', to='voyage.voyage'),
        ),
    ]
