# Generated by Django 4.2.1 on 2023-07-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('past', '0007_alter_enslaved_options'),
        ('document', '0008_alter_zoterovoyageconnection_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoteroEnslaverConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_range', models.CharField(blank=True, max_length=25, null=True)),
                ('enslaver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaver_zotero_connections', to='past.enslaveridentity')),
                ('zotero_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zotero_enslaver_connections', to='document.zoterosource')),
            ],
            options={
                'unique_together': {('zotero_source', 'enslaver', 'page_range')},
            },
        ),
        migrations.CreateModel(
            name='ZoteroEnslavedConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_range', models.CharField(blank=True, max_length=25, null=True)),
                ('enslaved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enslaved_zotero_connections', to='past.enslaved')),
                ('zotero_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zotero_enslaved_connections', to='document.zoterosource')),
            ],
            options={
                'unique_together': {('zotero_source', 'enslaved', 'page_range')},
            },
        ),
    ]
