# Generated by Django 4.2.1 on 2023-06-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyage', '0005_remove_voyagesourcesconnection_zotero_source'),
        ('past', '0002_june_1_2023_johnconnor_api'),
        ('document', '0008_remove_zoterosource_source_cnx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoterosource',
            name='enslaved_people',
            field=models.ManyToManyField(related_name='enslaved_zoterorefs', to='past.enslaved'),
        ),
        migrations.AlterField(
            model_name='zoterosource',
            name='enslavers',
            field=models.ManyToManyField(related_name='enslaver_zoterorefs', to='past.enslaveridentity'),
        ),
        migrations.AlterField(
            model_name='zoterosource',
            name='voyages',
            field=models.ManyToManyField(related_name='voyage_zoterorefs', to='voyage.voyage'),
        ),
    ]
