# Generated by Django 4.2.1 on 2024-01-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_source_manifest_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='zotero_url',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='document.sourcetype'),
        ),
    ]
