# Generated by Django 4.2.1 on 2023-07-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_zoteroenslaverconnection_zoteroenslavedconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoterosource',
            name='enslaved_people',
        ),
        migrations.RemoveField(
            model_name='zoterosource',
            name='enslavers',
        ),
        migrations.RemoveField(
            model_name='zoterosource',
            name='voyages',
        ),
    ]
