# Generated by Django 4.2.1 on 2023-07-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_remove_zoterosource_enslaved_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoteroenslavedconnection',
            name='page_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zoteroenslaverconnection',
            name='page_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zoterovoyageconnection',
            name='page_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
