# Generated by Django 4.2.1 on 2024-01-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_alter_source_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='has_published_manifest',
            field=models.BooleanField(default=False, verbose_name='Is there a published manifest?'),
        ),
        migrations.AlterField(
            model_name='source',
            name='manifest_content',
            field=models.JSONField(help_text='DCTerms imported from Zotero -- NOT the full manifest', null=True),
        ),
    ]
