# Generated by Django 4.2.1 on 2023-07-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_alter_zoteroenslavedconnection_page_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoterosource',
            name='short_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
