# Generated by Django 4.2.1 on 2023-07-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_zoterosource_short_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoterosource',
            name='is_legacy_source',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
