# Generated by Django 4.2.1 on 2024-01-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_source_uid_source_zotero_web_page_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='iiif_manifest_url',
        ),
        migrations.RemoveField(
            model_name='page',
            name='transcription',
        ),
    ]
