# Generated by Django 4.2.1 on 2023-07-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_zoterosource_is_legacy_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoterovoyageconnection',
            name='page_range',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
