# Generated by Django 4.2.1 on 2023-08-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_alter_zoterosource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoteroenslavedconnection',
            name='page_range',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='zoteroenslaverconnection',
            name='page_range',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
