# Generated by Django 4.2 on 2023-04-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Geographic Location Type',
                'verbose_name_plural': 'Geographic Location Types',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude of Centroid')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude of Centroid')),
                ('spatial_extent', models.JSONField(null=True, verbose_name='Geojson Polygon')),
                ('uid', models.IntegerField(unique=True)),
                ('child_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of', to='geo.place')),
                ('location_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_location', to='geo.locationtype', verbose_name='Location Type')),
            ],
            options={
                'verbose_name': 'Geographic Location',
                'verbose_name_plural': 'Geographic Locations',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.IntegerField(verbose_name='Dataset')),
                ('shortest_route', models.JSONField(null=True, verbose_name='Endpoint to endpoint route')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceofroute', to='geo.place', verbose_name='Alice')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetofroute', to='geo.place', verbose_name='Bob')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'unique_together': {('source', 'target', 'dataset')},
            },
        ),
        migrations.CreateModel(
            name='Adjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.IntegerField(null=True, verbose_name='Dataset')),
                ('distance', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Distance')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceof', to='geo.place', verbose_name='Alice')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetof', to='geo.place', verbose_name='Bob')),
            ],
            options={
                'verbose_name': 'Location Adjacency',
                'verbose_name_plural': 'Location Adjacencies',
                'unique_together': {('source', 'target', 'dataset')},
            },
        ),
    ]
