# Generated by Django 4.0.2 on 2022-05-27 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Broad region (Area) name')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude of Centroid')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude of Centroid')),
                ('value', models.IntegerField(unique=True, verbose_name='SPSS code')),
                ('show_on_map', models.BooleanField(default=True)),
                ('show_on_main_map', models.BooleanField(default=True)),
                ('show_on_voyage_map', models.BooleanField(default=True)),
                ('child_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentof', to='geo.location', verbose_name='Child of')),
                ('parent_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childof', to='geo.location', verbose_name='Parent of')),
            ],
            options={
                'verbose_name': 'Geographic Location',
                'verbose_name_plural': 'Geographic Locations',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Geographic Location Type')),
            ],
            options={
                'verbose_name': 'Geographic Location Type',
                'verbose_name_plural': 'Geographic Location Types',
            },
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Route name')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceof', to='geo.location', verbose_name='Alice')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetof', to='geo.location', verbose_name='Bob')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='spatial_extent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.polygon', verbose_name='Polygon'),
        ),
    ]
