# Generated by Django 4.2 on 2023-04-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationType',
            new_name='PlaceType',
        ),
        migrations.RemoveField(
            model_name='place',
            name='location_type',
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_place', to='geo.placetype', verbose_name='Location Type'),
        ),
    ]
