# Generated by Django 4.0.2 on 2022-05-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_location_location_type_alter_locationtype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='parent_of',
        ),
        migrations.AlterField(
            model_name='location',
            name='show_on_main_map',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='show_on_map',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='show_on_voyage_map',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
