# Generated by Django 4.0.2 on 2022-06-04 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0007_alter_location_child_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceof', to='geo.location', verbose_name='Alice')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetof', to='geo.location', verbose_name='Bob')),
            ],
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
