# Generated by Django 4.2.1 on 2023-11-03 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Export area name')),
                ('order_num', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('show_at_zoom', models.IntegerField()),
                ('show_on_map', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Import area name')),
                ('order_num', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('show_at_zoom', models.IntegerField()),
                ('show_on_map', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('order_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Import region name')),
                ('order_num', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('show_at_zoom', models.IntegerField()),
                ('show_on_map', models.BooleanField()),
                ('import_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.importarea')),
            ],
        ),
        migrations.CreateModel(
            name='ExportRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Export region name')),
                ('order_num', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('show_at_zoom', models.IntegerField()),
                ('show_on_map', models.BooleanField()),
                ('export_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.exportarea')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('embarked_slaves', models.FloatField(blank=True, null=True)),
                ('disembarked_slaves', models.FloatField(blank=True, null=True)),
                ('disembarkation_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.importregion')),
                ('embarkation_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.exportregion')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.nation')),
            ],
        ),
    ]
